### ISSUE TITLE
various sample rate and file format testing

### ISSUE THREAD

**Issue by seungheondoh** [minigb/key-tempo-prediction#1]
[mrtp.zip](https://github.com/minigb/gtzan-key-tempo-prediction/files/12444796/mrtp.zip)

For covering over the 22050 sampling rate and .mp3, flac file format, I attach sample dataset

**Comment by minigb** [comment]
Thank you for reporting the issue.

This is solved in [commit 6744bb2](https://github.com/minigb/madmom/commit/6744bb274e8f52fd0d6205b01be59c283fd5bdea) in [minigb/madmom](https://github.com/minigb/madmom), and [commit 708e336](https://github.com/minigb/key-tempo-prediction/commit/708e336250790aea3200adcc78a4f745a38d17ee)
